/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jkt.tv.main;

import com.jkt.lib.driven.MongoHandler;
import com.jkt.tv.data.Arduino;
import com.jkt.tv.data.FacebookApp;
import com.jkt.tv.data.YouTubeApp;
import com.panamahitek.PanamaHitek_Arduino;
import facebook4j.Facebook;
import facebook4j.FacebookException;
import facebook4j.FacebookFactory;
import facebook4j.auth.AccessToken;
import facebook4j.conf.ConfigurationBuilder;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.net.UnknownHostException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import sun.launcher.resources.launcher;

/**
 *
 * @author JuanCamilo
 */
public class JMain extends javax.swing.JFrame implements SerialPortEventListener {

    PanamaHitek_Arduino arduino;
    YouTubeApp youtube;

    static String[] params;

    /**
     * Creates new form JMain
     */
    public JMain() {
        initComponents();
        arduino = new PanamaHitek_Arduino();
        List<String> ports = arduino.getSerialPorts();
        for (String port : ports) {
            cSerial.addItem(port);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bSerial = new javax.swing.JButton();
        tSerial = new javax.swing.JTextField();
        cSerial = new javax.swing.JComboBox();
        bDatabase = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        bFacebook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bSerial.setText("Start Serial");
        bSerial.setEnabled(false);
        bSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSerialActionPerformed(evt);
            }
        });

        tSerial.setEnabled(false);
        tSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSerialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tSerial)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSerialActionPerformed(evt);
            }
        });

        bDatabase.setText("To Database");
        bDatabase.setEnabled(false);
        bDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDatabaseActionPerformed(evt);
            }
        });

        bClose.setText("Close");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        bFacebook.setText("Publish Facebook");
        bFacebook.setEnabled(false);
        bFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFacebookActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(bDatabase)
                .addGap(18, 18, 18)
                .addComponent(bFacebook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bClose))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cSerial)
                            .addComponent(bDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bFacebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSerialActionPerformed

    private void bSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSerialActionPerformed
        // TODO add your handling code here:
        String com = cSerial.getSelectedItem().toString().toUpperCase();
        if (bSerial.getText().equals("Start Serial")) {
            try {
                arduino.arduinoRX(com, 9600, this);
                bSerial.setText("Stop Serial");
            } catch (Exception ex) {
                Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                arduino.killArduinoConnection();
                bSerial.setText("Start Serial");
            } catch (Exception ex) {
                Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bSerialActionPerformed

    private void cSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSerialActionPerformed
        // TODO add your handling code here:
        bSerial.setEnabled(true);
    }//GEN-LAST:event_cSerialActionPerformed

    private void bDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDatabaseActionPerformed
        // TODO add your handling code here:
        try {
            MongoHandler mongo = new MongoHandler("TVInteractiva");
            mongo.insert(new FacebookApp("jk", "jkp", tSerial.getText()));
            tSerial.setText("Database Updated");
            bFacebook.setEnabled(false);
        } catch (UnknownHostException ex) {
            Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bDatabaseActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bCloseActionPerformed

    private void bFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFacebookActionPerformed
        // TODO add your handling code here:
        ConfigurationBuilder cb = new ConfigurationBuilder();
        cb.setDebugEnabled(true);
        cb.setOAuthAppId("1297407430303696");
        cb.setOAuthAppSecret("4dde7175e1787be7c61337ffeaf3ad21");
        cb.setOAuthAccessToken("EAASbZCDUDH9ABAIvu9OXM8xDsvTKbJ8nHpSJKp37IQo3ug9fk8jRAg5THsuSbE1hIcGK5LhMuZBOuYlNuu9Jg5crvBDMZBpKHR1Grl5B4hVZBK9HMilr3qVDdZBmvaalvSULJn7sXXzvDv9idbPBKstGNxot5Co0I063rcZBY3mwZDZD");
        cb.setOAuthPermissions("email,publish_stream,...");
        FacebookFactory ff = new FacebookFactory(cb.build());
        Facebook face = ff.getInstance();

        try {
            face.postStatusMessage(tSerial.getText());
            tSerial.setText("Published in Facebook");
            bDatabase.setEnabled(false);
        } catch (FacebookException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bFacebookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JMain().setVisible(true);
//                params = args;
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bDatabase;
    private javax.swing.JButton bFacebook;
    private javax.swing.JButton bSerial;
    private javax.swing.JComboBox cSerial;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tSerial;
    // End of variables declaration//GEN-END:variables

    @Override
    public void serialEvent(SerialPortEvent ev) {
        if (arduino.isMessageAvailable()) {
            String cad = arduino.printMessage();
            tSerial.setText(cad);
            if (!bDatabase.isEnabled()) {
                bDatabase.setEnabled(true);
            }
            if (!bFacebook.isEnabled()) {
                bFacebook.setEnabled(true);
            }
        }
    }
}
